/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComparableLineChart: typeof import('./src/components/echarts/ComparableLineChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FlexibleLineChart: typeof import('./src/components/echarts/FlexibleLineChart.vue')['default']
    ProgressIndicator: typeof import('./src/components/ProgressIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SunBurstResourceChart: typeof import('./src/components/echarts/SunBurstResourceChart.vue')['default']
    TextContainer: typeof import('./src/components/TextContainer.vue')['default']
  }
}

// For TSX support
declare global {
  const ComparableLineChart: typeof import('./src/components/echarts/ComparableLineChart.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElEmpty: typeof import('element-plus/es')['ElEmpty']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const FlexibleLineChart: typeof import('./src/components/echarts/FlexibleLineChart.vue')['default']
  const ProgressIndicator: typeof import('./src/components/ProgressIndicator.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SunBurstResourceChart: typeof import('./src/components/echarts/SunBurstResourceChart.vue')['default']
  const TextContainer: typeof import('./src/components/TextContainer.vue')['default']
}